version: "3.8"

networks:
  miniature-fishstick-net:
    name: ml4ds_net
    external: true

services:
  imt_tools:
    build: ./imt_tools
    container_name: imt_tools
    env_file:
      - .env
    ports:
        - 8080:8080
    networks:
        - miniature-fishstick-net